// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetConfig():Promise<string>;

export function OpenDirDialog():Promise<string>;

export function SaveConfig(arg1:string):Promise<boolean>;

export function Search(arg1:number,arg2:string):Promise<string>;
